apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    app: amq-demo-config.AMQ_DEMO_CLUSTER_1_NAME
  name: amq-demo-config.AMQ_DEMO_CLUSTER_1_NAME
  namespace: amq-demo-config.AMQ_DEMO_PROJECT_NAME
spec:
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  kafka:
    replicas: 3
    storage:
      type: ephemeral
    # ...
    listeners:
      - name: listener1
        port: 9094
        type: route
        tls: true
        # ...
    # ...
  
  

