apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: amq-test 
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-edit
  apiGroup: rbac.authorization.k8s.io
