kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
  namespace: amq-demo-config.AMQ_DEMO_PROJECT_NAME
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824